# Generated by Django 3.1.3 on 2020-11-17 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_release_date', models.DateField(default=datetime.date)),
                ('movie_upvotes', models.IntegerField(default=0)),
            ],
        ),
    ]
